name: joint-js
version: '${project.version}'
main: ru.smokingplaya.jointjs.Main
api-version: '1.16'
commands:
  joint:
    description: Controlling the plugin via commands
    usage: /joint <subCommand>
    permission: jointjs.use.command