name: joint-js
version: '${project.version}'
main: ru.smokingplaya.jointjs.Main
api-version: '1.16'
commands:
  jointreload:
    description: Reloads joint scripts
    usage: /<command>
    permission: sperma.everywhere